variables:
  ORD_SOUMET_TMPFS: "1G"
  ORD_SOUMET_M: "8G"
  ORD_SOUMET_C: "2"
  PHIL_VARIABLE: "toplevel value"
  USE_ENVIRONMENT: "${HOME}"
  USE_OTHER_YAML_VAR: "${PHIL_VARIABLE}"


before_script:
  - export BEFORE_SCRIPT_VAR=${HOME}
  - echo "This is the before script part"
  - echo "PHIL_VARIABLE=${PHIL_VARIABLE}"

demo_bernard:
  script:
    - echo "make"
    - echo "rouler un test"
    - env | sort
    - cd makefile_project
    - make
    - make test
  tags:
    - maybe-custom

demo_variables:
  script:
    - echo "YAML variable that uses environment '${USE_ENVIRONMENT}'.  We can see that when YAML variables are resolved, environment variables are not used"
    - echo "YAML variable that uses other YAML variable '${USE_OTHER_YAML_VAR}'"
    - echo "The value of BEFORE_SCRIPT_VAR is '${BEFORE_SCRIPT_VAR}'"
    - sleep 10
    - exit 88
  tags:
    - maybe-custom




      # no_mach:
      #   script:
      #     - sleep 20
      #    
      # empty_mach:
      #   variables:
      #     ORD_SOUMET_MACH: ""
      #   script:
      #     - echo "The value of ORD_SOUMET_MACH is '${ORD_SOUMET_MACH}'"
      #     - sleep 5

      # gpsc3:
      #   variables:
      #     ORD_SOUMET_MACH: gpsc3
      #     ORD_SOUMET_PROJECT: eccc_cmdd
      #   script:
      #     - sleep 20
      # 
      # underhill:
      #   variables:
      #     ORD_SOUMET_MACH: "underhill"
      #     ORD_SOUMET_C: "80"
      #   script:
      #     - sleep 20
      # 
      # robert:
      #   variables:
      #     ORD_SOUMET_MACH: "robert"
      #     ORD_SOUMET_C: "80"
      #   script:
      #     - sleep 20
      #     
      # ppp5:
      #   variables:
      #     ORD_SOUMET_MACH: "ppp5"
      #   script:
      #     - sleep 20
      #     
      # ppp6:
      #   variables:
      #     ORD_SOUMET_MACH: "ppp6"
      #   script:
      #     - sleep 20
