variables:
  ORD_SOUMET_MACH: "ppp5"
make:
  script:
    - cd makefile_project
    - make test
    - sleep 599
  tags:
    - ppp5
    
make2:
  variables:
    ORD_SOUMET_D: "ppp6"
  script:
    - sleep 30
  tags:
    - ppp5

