
    
underhill:
  variables:
    ORD_SOUMET_MACH: "underhill"
    ORD_SOUMET_TMPFS: "1G"
    ORD_SOUMET_M: "8G"
    ORD_SOUMET_C: "80"
  script:
    - sleep 20

robert:
  variables:
    ORD_SOUMET_MACH: "robert"
    ORD_SOUMET_TMPFS: "1G"
    ORD_SOUMET_M: "8G"
    ORD_SOUMET_C: "80"
  script:
    - sleep 20