make:
  variables:
    ORD_SOUMET_MACH: gpsc3
    ORD_SOUMET_PROJECT: eccc_cmdd
    ORD_SOUMET_TMPFS: "1G"
    ORD_SOUMET_M: "8G"
    ORD_SOUMET_C: "4"
    # ORD_SOUMET_IMAGE: eccc/eccc_all_default_ubuntu-18.04-amd64_latest
  script:
    - cd makefile_project
    - make test
    - sleep 300

