variables:
  ORD_SOUMET_MACH: "ppp5"
make:
  script:
    - cd makefile_project
    - make test
    - sleep 100
  tags:
    - asdfasdf

    
make2:
  variables:
    ORD_SOUMET_D: "ppp6"
  script:
    - sleep 100
  tags:
    - asdfasdf


